name: futsim
description: "FutSim - Simulador de Futebol"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI e ícones
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1

  # Estado e gerenciamento
  provider: ^6.1.2
  shared_preferences: ^2.3.1

  # Persistência (SAVE / HIVE)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # Utilitários
  intl: ^0.19.0
  meta: ^1.12.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # Dados do jogo (JSONs)
    - assets/data/

    # Assets gerais
    - assets/logos/
    - assets/rostos/
    - assets/icons/
    - assets/imagens/
    - assets/jogadores/
    - assets/clubes/
